name: auto-release
on:
  push:
    branches:
      - master
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Run test
        run: |
          python auto_release.py
      - name: Create release
        uses: "meeDamian/github-release@2.0"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          tag: "latest"
          name: Global.ini发布
          body: >
            Global.ini发布
          files: release/
