name: auto-release
on:
  push:
    branches:
      - master
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  GAME_VERSION: 3.17.0 PU

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Run test
        run: |
          echo 'GAME_VERSION<<EOF' >> $GITHUB_ENV
          python auto_release.py >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create release
        uses: "meeDamian/github-release@2.0"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          tag: "${{env.GAME_VERSION}}"
          name: Global.ini release
          body: >
            ### Changelog
            
            - Add more translations
            
            ### Contributors
            
            - Summerkirakira (妖精)
            
            - JASACOMB (小明)
            
            - KirimaSyrao (卡布)
            
            - Number238 (238)
            
            ### License
            
            - MIT
          files: release/
